# Generated by Django 5.2.8 on 2025-11-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSemanticConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_column",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "time_column",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metric_columns", models.JSONField(blank=True, default=list)),
                ("column_types", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_config",
                        to="analytics.dataset",
                    ),
                ),
            ],
        ),
    ]
